### ISSUE TITLE
Is this 100% compatible with the C# reference implementation?

### ISSUE THREAD

**Issue by rht** [cmekik/pyClarion#6]
The reference implementation, as in http://www.clarioncognitivearchitecture.com/downloads.
If not, what are the remaining TODOs?
I can't run the C# version (Mono is too heavy of a dependency on *nix) and would be happy to have the Python version.

If I were to estimate the complexity of the task based on the 6.0.5 version (Java) which is 9348 LOC, it would take a week to fully port it.

**Comment by cmekik** [comment]
This version is not based on any other implementation. It follows the book *Anatomy of the Mind* (OUP, 2016) by Ron Sun.

**Comment by rht** [comment]
I see. The latest released version was from 2012. And there was a 6.1.1 announcement 8 days ago (but would still be in the form of .dll). I will wait until the 6.1.1 release and port it then. Note: the .dll does not protect the source from being revealed via a dotnet decompiler. But a strong license such as GPLv3 does prevent private commercial derivative use.

**Comment by rht** [comment]
It would be informative to have this info in the README.md btw.
